# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: CocCoc.CocCoc
PackageVersion: 120.0.6099.234
PackageLocale: vi-VN
Publisher: Coc Coc Co., Ltd.
PackageName: Coc Coc
License: None
Copyright: Copyright 2018 Google LLC
ShortDescription: Coc Coc Browser
ManifestType: defaultLocale
ManifestVersion: 1.5.0
