# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: CocCoc.CocCoc
PackageVersion: 120.0.6099.234
PackageLocale: vi-VN
Publisher: Công ty TNHH Cốc Cốc
PackageName: Cốc Cốc
License: Proprietary
Copyright: Copyright 2018 Google LLC
ShortDescription: Cốc Cốc Browser is a freeware web browser developed by the Vietnamese company Cốc Cốc. It is based on the Chromium open-source code and is specifically tailored for the Vietnamese market.
ManifestType: defaultLocale
ManifestVersion: 1.5.0
